version: 2.1

jobs:
  # Job for setting up the backend
  setup-backend:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Install backend dependencies
          command: |
            cd backend
            npm install

  # Job for setting up the frontend
  setup-frontend:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Install frontend dependencies
          command: |
            cd frontend
            npm install

workflows:
  version: 2
  build_and_test:
    jobs:
      - setup-backend
      - setup-frontend